name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Update binaries
        run: |
          sudo apt update || true
          sudo apt install -y g++-aarch64-linux-gnu || true
          git clone --recursive https://github.com/uNetworking/uWebSockets.js.git
          cd uWebSockets.js
          sed -i 's/writeHeader("uWebSockets/\/\/writeHeader("uWebSockets/g'  ./uWebSockets/src/HttpResponse.h
          make
          git fetch origin binaries:binaries
          git checkout binaries
          rm *darwin*.node *win*.node
          cp dist/*.node .
          git remote add my https://github.com/tomasky/uWebSockets.js.git
          git pull my binaries
          git status
          git rev-parse master > source_commit
          git checkout master docs/index.d.ts && mv docs/index.d.ts .
          git config --global user.email "tomasky@gmail.com"
          git config --global user.name "tomasky"
          git commit -a -m "[GitHub Actions] Updated ${{ matrix.os }} binaries" || true
        
        
          git push "https://tomasky:${{ secrets.GITHUB_TOKEN }}@github.com/tomasky/uWebSockets.js" binaries
