name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Update binaries
        run: |
          sudo apt update || true
          sudo apt install -y g++-aarch64-linux-gnu || true
          sudo apt install -y patchelf
          git clone https://github.com/matrix1001/glibc-all-in-one
          cd glibc-all-in-one && ./update_list && ./download_old 2.34-0ubuntu3_amd64 
          sudo patchelf --set-interpreter ./libs/2.34-0ubuntu3_amd64/ld-linux-x86-64.so.2    ./bin   
          sudo patchelf --set-rpath  ./libs/2.34-0ubuntu3_amd64/ ./bin

          cd ../ && git clone --recursive https://github.com/uNetworking/uWebSockets.js.git
          cd uWebSockets.js
          sed -i 's/writeHeader("uWebSockets/\/\/writeHeader("uWebSockets/g'  ./uWebSockets/src/HttpResponse.h
          make -j 5
          
          git remote add my https://github.com/tomasky/uWebSockets.js.git
          git fetch my binaries:binaries
          git checkout my/binaries
          git config --global user.email "tomasky@gmail.com"
          git config --global user.name "tomasky"
          cp dist/*.node .
          git status
          git rev-parse master > source_commit
          git checkout master docs/index.d.ts && mv docs/index.d.ts .
           
          git add *108.node
          git commit -a -m "[GitHub Actions] Updated ${{ matrix.os }} binaries" || true
          git checkout -b temp
        
          git push "https://tomasky:${{ secrets.GITHUB_TOKEN }}@github.com/tomasky/uWebSockets.js" temp:binaries
