name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Update binaries
        run: |
          sudo apt update || true
          sudo apt install -y g++-aarch64-linux-gnu || true
          git clone --recursive https://github.com/uNetworking/uWebSockets.js.git
          cd uWebSockets.js
          git fetch origin binaries:binaries
          git checkout binaries
          cp dist/*.node .
          git status
          git rev-parse master > source_commit
          git checkout master docs/index.d.ts && mv docs/index.d.ts .
         
          git commit -a -m "[GitHub Actions] Updated ${{ matrix.os }} binaries" || true
          git push "https://tomasky:${{ secrets.SECRET }}@github.com/tomasky/uWebSockets.js" binaries
